FROM golang:latest

WORKDIR /go/bin/golang-mongodb-poc

COPY . .

RUN go get github.com/canthefason/go-watcher

RUN go install github.com/canthefason/go-watcher/cmd/watcher  

WORKDIR /go/bin/golang-mongodb-poc/cmd/golang-poc

EXPOSE 3333

ENTRYPOINT [ "watcher" ]