FROM golang:1.19

WORKDIR /go/bin/golang-mongodb

COPY . .

RUN go get github.com/canthefason/go-watcher

RUN go install github.com/canthefason/go-watcher/cmd/watcher  

WORKDIR /go/bin/golang-mongodb/cmd/golang-poc

EXPOSE 3333

ENTRYPOINT [ "watcher" ]