version: '3'

services:
  app:
    container_name: go-mongodb-poc
    build: 
      context: .
      dockerfile: Dockerfile-dev
    env_file: ./config/.env
    depends_on:
      - mongo
    volumes:
      - .:/go/bin/golang-mongodb
    ports:
      - 3333:3333

  mongo:
    container_name: go-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_PASSWORD: golang
      MONGO_INITDB_ROOT_USERNAME: golang
      MONGO_INITDB_DATABASE: mock
    ports:
      - 27017:27017
    
